class AddDimIToHartmanValueProfile < ActiveRecord::Migration
  def self.up
    change_table :hartman_value_profiles do |t|
      t.integer :dif_v
      t.integer :dim_i_v
      t.integer :dim_e_v
      t.integer :dim_s_v
      t.integer :int_v
      t.integer :int_i_v
      t.integer :int_e_v
      t.integer :int_s_v
      t.integer :dim_v
      t.integer :di_v
      t.integer :dis_v
      t.float :dim_percent_v
      t.float :int_percent_v
      t.integer :positive_i_v
      t.integer :positive_e_v
      t.integer :positive_s_v
      t.integer :positive_total_v
      t.integer :negative_i_v
      t.integer :negative_e_v
      t.integer :negative_s_v
      t.integer :negative_total_v
      t.float :ai_percent_v
      t.integer :dif_s
      t.integer :dim_i_s
      t.integer :dim_e_s
      t.integer :dim_s_s
      t.integer :int_s
      t.integer :int_i_s
      t.integer :int_e_s
      t.integer :int_s_s
      t.integer :dim_s
      t.integer :di_s
      t.integer :dis_s
      t.float :dim_percent_s
      t.float :int_percent_s
      t.integer :positive_i_s
      t.integer :positive_e_s
      t.integer :positive_s_s
      t.integer :positive_total_s
      t.integer :negative_i_s
      t.integer :negative_e_s
      t.integer :negative_s_s
      t.integer :negative_total_s
      t.float :ai_percent_s
      t.integer :vq_left
      t.integer :vq_right
      t.integer :sq_left
      t.integer :sq_right
      t.float :bqr1
      t.float :bqa1
      t.float :bqr2
      t.float :bqa2
      t.float :cq1
      t.float :cq2
      t.float :dif1_over_dif2
    end
  end

  def self.down
    change_table :hartman_value_profiles do |t|
      t.remove :dif_v
      t.remove :dim_i_v
      t.remove :dim_e_v
      t.remove :dim_s_v
      t.remove :int_v
      t.remove :int_i_v
      t.remove :int_e_v
      t.remove :int_s_v
      t.remove :dim_v
      t.remove :di_v
      t.remove :dis_v
      t.remove :dim_percent_v
      t.remove :int_percent_v
      t.remove :positive_i_v
      t.remove :positive_e_v
      t.remove :positive_s_v
      t.remove :positive_total_v
      t.remove :negative_i_v
      t.remove :negative_e_v
      t.remove :negative_s_v
      t.remove :negative_total_v
      t.remove :ai_percent_v
      t.remove :dif_s
      t.remove :dim_i_s
      t.remove :dim_e_s
      t.remove :dim_s_s
      t.remove :int_s
      t.remove :int_i_s
      t.remove :int_e_s
      t.remove :int_s_s
      t.remove :dim_s
      t.remove :di_s
      t.remove :dis_s
      t.remove :dim_percent_s
      t.remove :int_percent_s
      t.remove :positive_i_s
      t.remove :positive_e_s
      t.remove :positive_s_s
      t.remove :positive_total_s
      t.remove :negative_i_s
      t.remove :negative_e_s
      t.remove :negative_s_s
      t.remove :negative_total_s
      t.remove :ai_percent_s
      t.remove :vq_left
      t.remove :vq_right
      t.remove :sq_left
      t.remove :sq_right
      t.remove :bqr1
      t.remove :bqa1
      t.remove :bqr2
      t.remove :bqa2
      t.remove :cq1
      t.remove :cq2
      t.remove :dif1_over_dif2
    end
  end
end
